### PR TITLE
Port to JAX

### PR DESCRIPTION
**Pull request by Gattocrucco**

### CODE REVIEW

**Comment by alecandido** [comment]
I would suggest to lift `tests-requirements.txt` from `.github/workflows` to the top level: exposing it would make it easier for other people to run the tests manually as well. Same thing for `requirements-docs.txt`

Furthermore, I would encode there only those that are not already contained in `setup.py`: in principle those are already coming as dependencies, and you should get them just installing your package with:
```sh
pip install .
```

**Comment by alecandido** [comment]
However, even `setuptools` is [moving towards](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html) the standard `pyproject.toml`.

If you use `pyproject.toml` you can encode `docs` and `test` deps in the table `[project.optional-dependencies]`, and you can install as extras:
```sh
pip install '.[docs]'
pip install '.[test]'
pip install '.[docs,test]'
```

I still prefer Poetry, and for those I would use development dependencies, rather than extras; but it's fine as well, and it has its own advantages.
But I'm not suggesting you to use Poetry, it might be a massive time consuming task (if you wish, and I believe not, I can setup for you in a separate PR, it might take little to me, and then you can decide).

**Comment by Gattocrucco** [comment]
> I would suggest to lift `tests-requirements.txt` from `.github/workflows` to the top level: exposing it would make it easier for other people to run the tests manually as well. Same thing for `requirements-docs.txt`
> 
> Furthermore, I would encode there only those that are not already contained in `setup.py`: in principle those are already coming as dependencies, and you should get them just installing your package with:
> 
> ```shell
> pip install .
> ```

To run the tests yourself you can use the top-level `requirements.txt`. The `*requirements*` files in `.github/workflow` are intentionally separate to tweak the CI environment.

**Comment by alecandido** [comment]
> The `*requirements*` files in `.github/workflow` are intentionally separate to tweak the CI environment.

But actually why you need to tweak? The best scenario would be to run the tests in the same environment of your users.

**Comment by Gattocrucco** [comment]
> But actually why you need to tweak? The best scenario would be to run the tests in the same environment of your users.

Two reasons:

1. I don't install everything in CI. I did this instinctively for efficiency, but in hindsight it doesn't really makes a difference, so I could change this and use `/requirements.txt`.
2. Some tests run on outdated environments with the oldest supported versions of the dependencies.

**Comment by alecandido** [comment]
Ok, then I see the purpose of `old`, but I would put it top-level, as a reference for the user (while I'd remove `.github/workflows/tests-requirements.txt`).

However, it is just an opinion, you do as you prefer :)

**Pull request merged**
